name: CI/CD Pipeline to Vercel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Deploy to Vercel
        run: |
          npx vercel@latest --prod --token=${{ secrets.VERCEL_TOKEN }} --yes \
            --scope ${{ secrets.VERCEL_ORG_ID }} \
            -m "githubCommitSha=${{ github.sha }}" \
            -m "githubCommitRef=${{ github.ref_name }}"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}